name: Pull Request Labeling
on: pull_request
jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/labeler@v4
          with:
            configuration-path: .github/labeler.yml
            sync-labels: true
            repo-token: "${{ secrets.GITHUB_TOKEN }}"
            
  size-label:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: size-label
        uses: "pascalgn/size-label-action@v0.4.2"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          sizes: >
            {
              "0": "XS",
              "20": "S",
              "50": "M",
              "200": "L",
              "800": "XL",
              "2000": "XXL"
            }